#!/bin/sh -e



/tmp/setup/files/scripts/apt \&&
/tmp/setup/files/scripts/locale \&&
/tmp/setup/files/scripts/packages \&&
/tmp/setup/files/scripts/supervisor \&&
/tmp/setup/files/scripts/inittab \&&
/tmp/setup/files/scripts/sshd 